### ISSUE TITLE
不开个评论吗？

### ISSUE THREAD

**Issue by hongtaoh** [Ashleygua/Ashleygua.github.io#1]
哈哈

**Comment by hongtaoh** [comment]
顺便问一句，我可以把你的网站放在我的博客里吗？https://hongtaoh.com/cn/2021/03/02/personal-website-tutorial/。

我想列出根据这篇帖子把网站弄好的例子。不方便也没事的。

**Comment by Ashleygua** [comment]
> 顺便问一句，我可以把你的网站放在我的博客里吗？[https://hongtaoh.com/cn/2021/03/02/personal-website-tutorial/。](https://hongtaoh.com/cn/2021/03/02/personal-website-tutorial/%E3%80%82)
> 
> 我想列出根据这篇帖子把网站弄好的例子。不方便也没事的。

好的, 没问题。

ps. 我只是还不知道怎么开评论

**Comment by hongtaoh** [comment]
@Ashleygua 好的，已经把你的博客添加上去了。网址的话，把那个句号去掉就没事了。我把你的评论功能弄好了。

**Comment by Ashleygua** [comment]
谢谢!
